<a href="https://colab.research.google.com/github/DrabberSP/Actividad-4/blob/main/Act4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
# Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [ ]:
# Cargar archivo .xlsx desde equipo
df=pd.read_csv('MicroRetailer_Final.csv')
df.head(5)

Regresión Lineal 3

In [ ]:
# Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep1=df[['163_number_high_perishable_products','145_number_direct_competitors']]
Var_Dep1=df['172_supplier_frequency']

In [ ]:
# Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
# Verificamos la función relacionada al modelo
type(model)

sklearn.linear_model._base.LinearRegression

In [ ]:
# Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep1, y=Var_Dep1)

LinearRegression()

In [ ]:
# Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['163_number_high_perishable_products',
        '145_number_direct_competitors'], dtype=object),
 'n_features_in_': 2,
 'coef_': array([0.03627443, 0.01841275]),
 '_residues': 1796.9577825559163,
 'rank_': 2,
 'singular_': array([363.13459128,  76.1028141 ]),
 'intercept_': 2.576562804804153}

In [ ]:
# Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R2 de determinación
model.score(Vars_Indep1,Var_Dep1)

0.09148476849031906

Regresión Logística 3

In [ ]:
# Redefinimos las variables
X=Vars_Indep1
y=Var_Dep1

In [ ]:
# Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=None)

In [ ]:
# Se escalan todos los datos
escalar = StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
# Verificamos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
# Entrenamos el modelo
algoritmo.fit(X_train , y_train)

LogisticRegression()

In [ ]:
# Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array([7., 1., 1., 7., 1., 1., 7., 7., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 7., 1., 7., 1., 1., 1., 1., 1., 1., 7., 1., 1., 1.,
       1., 1., 1., 7., 1., 1., 1., 1., 1., 7., 1., 1., 1., 1., 1., 1., 1.,
       1., 7., 1., 7., 1., 7., 1., 5., 1., 1., 1., 7., 1., 1., 7., 7., 1.,
       1., 1., 1., 7., 1., 1., 1., 1., 1., 7., 7., 7., 7., 1., 1., 1., 7.,
       1., 1., 1., 1., 1., 1., 7., 7., 1., 1., 1., 1., 7., 1.])

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[33  0  0  0  0  8]
 [19  0  0  0  0  8]
 [ 4  0  0  0  0  2]
 [ 2  0  0  0  0  0]
 [ 3  0  0  0  1  0]
 [13  0  0  0  0  6]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="weighted", pos_label="yes")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.27306852306852303


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.40404040404040403


In [ ]:
# Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="weighted", pos_label="yes")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.40404040404040403


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
